"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SocketEventType = void 0;
var SocketEventType;
(function (SocketEventType) {
    SocketEventType["WppChatStarted"] = "wpp_chat_started";
    SocketEventType["WppChatFinished"] = "wpp_chat_finished";
    SocketEventType["WppChatTransfer"] = "wpp_chat_transfer";
    SocketEventType["WppMessage"] = "wpp_message";
    SocketEventType["WppMessageEdit"] = "wpp_message_edit";
    SocketEventType["WppMessageDelete"] = "wpp_message_delete";
    SocketEventType["WppMessageStatus"] = "wpp_message_status";
    SocketEventType["WppMessageReaction"] = "wpp_message_reaction";
    SocketEventType["WppContactMessagesRead"] = "wpp_contact_messages_read";
    SocketEventType["WwebjsQr"] = "wwebjs_qr";
    SocketEventType["WwebjsAuth"] = "wwebjs_auth";
    SocketEventType["ReportStatus"] = "report_status";
    SocketEventType["InternalChatStarted"] = "internal_chat_started";
    SocketEventType["InternalChatFinished"] = "internal_chat_finished";
    SocketEventType["InternalMessage"] = "internal_message";
    SocketEventType["InternalMessageEdit"] = "internal_message_edit";
    SocketEventType["InternalMessageDelete"] = "internal_message_delete";
    SocketEventType["InternalMessageStatus"] = "internal_message_status";
})(SocketEventType || (exports.SocketEventType = SocketEventType = {}));
